### ISSUE TITLE
issues with cloning via ssh

### ISSUE THREAD

**Issue by tungstengmd** [comfysage/chaivim#7]
it doesn't start properly, i get this error
![image](https://github.com/user-attachments/assets/96fd2809-084a-46cd-a9bc-691faa3e9abf)

**Comment by tungstengmd** [comment]
and yes it is built with luajit

**Comment by comfysage** [comment]
it seems i forgot to update the start branch after a recent rework.
i just fixed this with 58ebe53.
could you try updating your config?
i hope this fixed your issues.

**Comment by tungstengmd** [comment]
![image](https://github.com/user-attachments/assets/be8cbadd-4b40-4458-ba29-0dd998c76619)
now i get this ._.

**Comment by tungstengmd** [comment]
for every plugin btw

**Comment by comfysage** [comment]
> ![image](https://github.com/user-attachments/assets/be8cbadd-4b40-4458-ba29-0dd998c76619)
> now i get this ._.

this seems like you're having issues establishing an ssh connection with github.

could you try cloning evergarden manually like this to see if this is the issue:
```bash
git clone git@github.com:comfysage/evergarden.git ~/evergarden
```

**Comment by tungstengmd** [comment]
yeah it is i can't clone via ssh only https ;-;

**Comment by comfysage** [comment]
take a look at this gist (https://gist.github.com/comfysage/83fa0d1bde3d75192d1df956bf368849) to setup ssh on your system.

also take a look at these docs (https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey).

**Comment by tungstengmd** [comment]
i set it up :D
